language: ruby

before_install: "gem install bones"
install:        "rake gem:install_dependencies"

script: "rake"

rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.6.0
